
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://rukblwwidsndgcrxxcvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1a2Jsd3dpZHNuZGdjcnh4Y3ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDg1MzYsImV4cCI6MjA2NTgyNDUzNn0.kmn7VRi-gW-9YMElMXpannQ7t3Ot7Rw7uN9f45ImQHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
